-- nombre base de datos
use MejoresJugadores 

-- futbolistas

create table futbolistas(

futbolista_id int auto_increment not null,
pais_id int not null,
nombres varchar(100),
apellidos varchar(100),
goles int not null,
asistencias int not null,
partidos_jugados int not null,
puesto varchar(100),
edad int not null,
equipo_id int, 
PRIMARY KEY (futbolista_id),

 CONSTRAINT fk_futbolistas_equipos FOREIGN KEY (equipo_id) REFERENCES equipos(equipo_id),
 CONSTRAINT fk_futbolistas_paises FOREIGN KEY (pais_id) REFERENCES paises(pais_id)

);

--  paises
CREATE TABLE paises (
    pais_id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_pais VARCHAR(2) NOT NULL,
    nombre_pais VARCHAR(100) NOT NULL
);

INSERT INTO paises (codigo_pais, nombre_pais) VALUES
('AF', 'Afganistán'),
('AL', 'Albania'),
('DZ', 'Argelia'),
('AS', 'Samoa Americana'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguila'),
('AQ', 'Antártida'),
('AG', 'Antigua y Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaiyán'),
('BS', 'Bahamas'),
('BH', 'Baréin'),
('BD', 'Bangladés'),
('BB', 'Barbados'),
('BY', 'Bielorrusia'),
('BE', 'Bélgica'),
('BZ', 'Belice'),
('BJ', 'Benín'),
('BM', 'Bermudas'),
('BT', 'Bután'),
('BO', 'Bolivia'),
('BA', 'Bosnia y Herzegovina'),
('BW', 'Botsuana'),
('BV', 'Isla Bouvet'),
('BR', 'Brasil'),
('IO', 'Territorio Británico del Océano Índico'),
('BN', 'Brunéi'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Camboya'),
('CM', 'Camerún'),
('CA', 'Canadá'),
('CV', 'Cabo Verde'),
('KY', 'Islas Caimán'),
('CF', 'República Centroafricana'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Isla de Navidad'),
('CC', 'Islas Cocos'),
('CO', 'Colombia'),
('KM', 'Comoras'),
('CG', 'República del Congo'),
('CD', 'República Democrática del Congo'),
('CK', 'Islas Cook'),
('CR', 'Costa Rica'),
('CI', 'Costa de Marfil'),
('HR', 'Croacia'),
('CU', 'Cuba'),
('CW', 'Curazao'),
('CY', 'Chipre'),
('CZ', 'República Checa'),
('DK', 'Dinamarca'),
('DJ', 'Yibuti'),
('DM', 'Dominica'),
('DO', 'República Dominicana'),
('EC', 'Ecuador'),
('EG', 'Egipto'),
('SV', 'El Salvador'),
('GQ', 'Guinea Ecuatorial'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Etiopía'),
('FK', 'Islas Malvinas'),
('FO', 'Islas Feroe'),
('FJ', 'Fiyi'),
('FI', 'Finlandia'),
('FR', 'Francia'),
('GF', 'Guayana Francesa'),
('PF', 'Polinesia Francesa'),
('TF', 'Territorios Australes Franceses'),
('GA', 'Gabón'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Alemania'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Grecia'),
('GL', 'Groenlandia'),
('GD', 'Granada'),
('GP', 'Guadalupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haití'),
('HM', 'Islas Heard y McDonald'),
('VA', 'Ciudad del Vaticano'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungría'),
('IS', 'Islandia'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Irán'),
('IQ', 'Irak'),
('IE', 'Irlanda'),
('IM', 'Isla de Man'),
('IL', 'Israel'),
('IT', 'Italia'),
('JM', 'Jamaica'),
('JP', 'Japón'),
('JE', 'Jersey'),
('JO', 'Jordania'),
('KZ', 'Kazajstán'),
('KE', 'Kenia'),
('KI', 'Kiribati'),
('KP', 'Corea del Norte'),
('KR', 'Corea del Sur'),
('KW', 'Kuwait'),
('KG', 'Kirguistán'),
('LA', 'Laos'),
('LV', 'Letonia'),
('LB', 'Líbano'),
('LS', 'Lesoto'),
('LR', 'Liberia'),
('LY', 'Libia'),
('LI', 'Liechtenstein'),
('LT', 'Lituania'),
('LU', 'Luxemburgo'),
('MO', 'Macao'),
('MK', 'Macedonia del Norte'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malasia'),
('MV', 'Maldivas'),
('ML', 'Malí'),
('MT', 'Malta'),
('MH', 'Islas Marshall'),
('MQ', 'Martinica'),
('MR', 'Mauritania'),
('MU', 'Mauricio'),
('YT', 'Mayotte'),
('MX', 'México'),
('FM', 'Micronesia'),
('MD', 'Moldavia'),
('MC', 'Mónaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Marruecos'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Países Bajos'),
('NC', 'Nueva Caledonia'),
('NZ', 'Nueva Zelanda'),
('NI', 'Nicaragua'),
('NE', 'Níger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Isla Norfolk'),
('MP', 'Islas Marianas del Norte'),
('NO', 'Noruega'),
('OM', 'Omán'),
('PK', 'Pakistán'),
('PW', 'Palau'),
('PS', 'Palestina'),
('PA', 'Panamá'),
('PG', 'Papúa Nueva Guinea'),
('PY', 'Paraguay'),
('PE', 'Perú'),
('PH', 'Filipinas'),
('PN', 'Pitcairn'),
('PL', 'Polonia'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Catar'),
('RE', 'Reunión'),
('RO', 'Rumania'),
('RU', 'Rusia'),
('RW', 'Ruanda'),
('BL', 'San Bartolomé'),
('SH', 'Santa Elena'),
('KN', 'San Cristóbal y Nieves'),
('LC', 'Santa Lucía'),
('MF', 'San Martín'),
('PM', 'San Pedro y Miquelón'),
('VC', 'San Vicente y las Granadinas'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Santo Tomé y Príncipe'),
('SA', 'Arabia Saudita'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leona'),
('SG', 'Singapur'),
('SX', 'Sint Maarten'),
('SK', 'Eslovaquia'),
('SI', 'Eslovenia'),
('SB', 'Islas Salomón'),
('SO', 'Somalia'),
('ZA', 'Sudáfrica'),
('GS', 'Islas Georgias del Sur y Sandwich del Sur'),
('SS', 'Sudán del Sur'),
('ES', 'España'),
('LK', 'Sri Lanka'),
('SD', 'Sudán'),
('SR', 'Surinam'),
('SJ', 'Svalbard y Jan Mayen'),
('SZ', 'Suazilandia'),
('SE', 'Suecia'),
('CH', 'Suiza'),
('SY', 'Siria'),
('TW', 'Taiwán'),
('TJ', 'Tayikistán'),
('TZ', 'Tanzania'),
('TH', 'Tailandia'),
('TL', 'Timor Oriental'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad y Tobago'),
('TN', 'Túnez'),
('TR', 'Turquía'),
('TM', 'Turkmenistán'),
('TC', 'Islas Turcas y Caicos'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ucrania'),
('AE', 'Emiratos Árabes Unidos'),
('GB', 'Reino Unido'),
('US', 'Estados Unidos'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistán'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('VG', 'Islas Vírgenes Británicas'),
('VI', 'Islas Vírgenes de los Estados Unidos'),
('WF', 'Wallis y Futuna'),
('EH', 'Sahara Occidental'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabue');


-- equipos

create table equipos(
equipo_id int not null auto_increment,
nombre varchar(150),

constraint equipos_pk PRIMARY KEY (equipo_id)

)
ENGINE=InnoDB

DEFAULT CHARSET=utf8mb4

COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO equipos values
(null, 'ADT'),
(null, 'Alianza Atlético'),
(null, 'Alianza Lima'),
(null, 'Alianza Universidad'),
(null, 'Atlético Grau'),
(null, 'Ayacucho FC'),
(null,'Cienciano'),
(null,'Comerciantes Unidos'),
(null, 'Cusco FC'),
(null, 'Deportivo Garcilaso'),
(null, 'FBC Melgar'),
(null, 'Juan Pablo II College'),
(null, 'Los Chankas'),
(null, 'Sport Boys'),
(null,'Sport Huancayo'),
(null,'Sporting Cristal'),
(null, 'Universitario'),
(null, 'UTC');


-- select futbolistas metodo listar
SELECT f.*, e.nombre AS Equipo, p.nombre_pais as Pais, p.codigo_pais 
FROM futbolistas f 
LEFT JOIN equipos e ON f.equipo_id = e.equipo_id 
LEFT JOIN paises p ON f.pais_id = p.pais_id

select * from  mejoresjugadores.equipos where equipo_id = 19

--usp

-- select goleadores metodo listar
select f.futbolista_id, f.nombres , f.apellidos , e.nombre as Equipo , f.goles , f.partidos_jugados , f.edad , f.puesto, p.nombre_pais as pais
from mejoresjugadores.futbolistas f join mejoresjugadores.paises p 
on f.pais_id = p.pais_id 
join mejoresjugadores.equipos e 
on f.equipo_id = e.equipo_id 
where f.goles >=1
order by f.goles desc, f.partidos_jugados , f.apellidos asc


-- --select asistentes metodo listar
select f.futbolista_id, f.nombres , f.apellidos , e.nombre as Equipo , f.asistencias, f.partidos_jugados , f.edad , f.puesto , p.nombre_pais as pais
from mejoresjugadores.futbolistas f join mejoresjugadores.paises p 
on f.pais_id = p.pais_id 
join mejoresjugadores.equipos e 
on f.equipo_id = e.equipo_id 
where f.asistencias  >=1

order by f.asistencias desc, f.partidos_jugados asc, f.apellidos asc
